# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04grpc\"J\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x05\x12\x14\n\x0cis_superuser\x18\x04 \x01(\x05\"\x1c\n\x0bUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t29\n\x0bUserService\x12*\n\x07GetUser\x12\x11.grpc.UserRequest\x1a\n.grpc.User\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_USERREQUEST = DESCRIPTOR.message_types_by_name['UserRequest']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:grpc.User)
  })
_sym_db.RegisterMessage(User)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:grpc.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=20
  _USER._serialized_end=94
  _USERREQUEST._serialized_start=96
  _USERREQUEST._serialized_end=124
  _USERSERVICE._serialized_start=126
  _USERSERVICE._serialized_end=183
# @@protoc_insertion_point(module_scope)
